DROP SCHEMA IF EXISTS fraud CASCADE;
CREATE SCHEMA fraud;
SET search_path = fraud;

CREATE TABLE customers (
    customer_id UUID PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    phone_number TEXT,
    kyc_status TEXT NOT NULL,
    risk_tier TEXT NOT NULL,
    country_code CHAR(2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE accounts (
    account_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL REFERENCES customers(customer_id),
    account_type TEXT NOT NULL,
    account_status TEXT NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at TIMESTAMPTZ
);

CREATE TABLE merchants (
    merchant_id UUID PRIMARY KEY,
    merchant_name TEXT NOT NULL,
    merchant_category TEXT NOT NULL,
    country_code CHAR(2) NOT NULL,
    onboarding_risk_score NUMERIC(5,2) NOT NULL,
    merchant_status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment_methods (
    payment_method_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL REFERENCES customers(customer_id),
    method_type TEXT NOT NULL,
    card_bin TEXT,
    card_last4 TEXT,
    billing_country CHAR(2) NOT NULL,
    method_status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE device_fingerprints (
    device_id UUID PRIMARY KEY,
    customer_id UUID NOT NULL REFERENCES customers(customer_id),
    device_hash TEXT NOT NULL,
    ip_country CHAR(2) NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE transactions (
    transaction_id UUID PRIMARY KEY,
    account_id UUID NOT NULL REFERENCES accounts(account_id),
    customer_id UUID NOT NULL REFERENCES customers(customer_id),
    merchant_id UUID NOT NULL REFERENCES merchants(merchant_id),
    payment_method_id UUID NOT NULL REFERENCES payment_methods(payment_method_id),
    device_id UUID NOT NULL REFERENCES device_fingerprints(device_id),
    amount NUMERIC(12,2) NOT NULL,
    currency CHAR(3) NOT NULL,
    transaction_status TEXT NOT NULL,
    authorization_status TEXT NOT NULL,
    risk_score NUMERIC(5,2) NOT NULL,
    initiated_at TIMESTAMPTZ NOT NULL,
    settled_at TIMESTAMPTZ
);

CREATE TABLE transaction_events (
    event_id UUID PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id),
    event_type TEXT NOT NULL,
    event_at TIMESTAMPTZ NOT NULL,
    event_payload JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE risk_rules (
    rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code TEXT NOT NULL UNIQUE,
    rule_name TEXT NOT NULL,
    severity TEXT NOT NULL,
    threshold_value NUMERIC(12,2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE fraud_alerts (
    alert_id UUID PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id),
    rule_id INTEGER NOT NULL REFERENCES risk_rules(rule_id),
    alert_status TEXT NOT NULL,
    priority TEXT NOT NULL,
    alert_score NUMERIC(5,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ
);

CREATE TABLE manual_reviews (
    review_id UUID PRIMARY KEY,
    alert_id UUID NOT NULL REFERENCES fraud_alerts(alert_id),
    analyst_id TEXT NOT NULL,
    review_status TEXT NOT NULL,
    decision TEXT,
    decision_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at TIMESTAMPTZ
);

CREATE TABLE chargebacks (
    chargeback_id UUID PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES transactions(transaction_id),
    reason_code TEXT NOT NULL,
    dispute_amount NUMERIC(12,2) NOT NULL,
    chargeback_status TEXT NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    won_by_platform BOOLEAN
);

CREATE TABLE audit_log (
    audit_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    operation TEXT NOT NULL,
    row_pk TEXT NOT NULL,
    changed_by TEXT NOT NULL DEFAULT current_user,
    old_data JSONB,
    new_data JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
